import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  // Cria categorias
  const categoriaEletronicos = await prisma.categoria.upsert({
    where: { id: 1 },
    update: {},
    create: { nome: 'Eletrônicos' },
  });

  const categoriaModa = await prisma.categoria.upsert({
    where: { id: 2 },
    update: {},
    create: { nome: 'Moda' },
  });

  const categoriaCasaDeco = await prisma.categoria.upsert({
    where: { id: 3 },
    update: {},
    create: { nome: 'Casa e Decoração' },
  });

  const categoriaBeleza = await prisma.categoria.upsert({
    where: { id: 4 },
    update: {},
    create: { nome: 'Beleza' },
  });

  const marcaX = await prisma.marca.upsert({
    where: { id: 1 },
    update: {},
    create: { nome: 'MarcaX' },
  });

  // Produtos eletrônicos
  await prisma.produto.createMany({
    data: [
      {
        nome: 'Fone Gamer XYZ',
        descricao: 'Fone com som surround',
        preco: 799.99,
        precoOriginal: 999.99,
        frete: 20,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'XYZ',
        numeroModelo: '1234',
        condicao: 'novo',
        dimensoes: '20x10x15 cm',
        garantia: '12 meses',
        voltagem: '110V',
        localizacaoProduto: 'SP',
        quantidade: 50,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Smartphone ABC',
        descricao: 'Smartphone com câmera 108MP',
        preco: 1599.99,
        precoOriginal: 1899.99,
        frete: 25,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'ABC',
        numeroModelo: '5678',
        condicao: 'novo',
        dimensoes: '15x7x1 cm',
        garantia: '24 meses',
        voltagem: '110V',
        localizacaoProduto: 'RJ',
        quantidade: 30,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Notebook Ultra X',
        descricao: 'Notebook com tela 4K e processador i9',
        preco: 4999.99,
        precoOriginal: 5999.99,
        frete: 40,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'Ultra X',
        numeroModelo: '9999',
        condicao: 'novo',
        dimensoes: '35x24x2 cm',
        garantia: '12 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'MG',
        quantidade: 15,
        quantidadeVarejo: 1,
      },
      {
        nome: 'TV 4K OLED 55"',
        descricao: 'Televisão com painel OLED e resolução 4K',
        preco: 3499.99,
        precoOriginal: 4199.99,
        frete: 50,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'OLED55',
        numeroModelo: 'TV123',
        condicao: 'novo',
        dimensoes: '122x71x5 cm',
        garantia: '24 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'BA',
        quantidade: 10,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Caixa de Som Bluetooth BassX',
        descricao: 'Caixa de som potente com graves reforçados',
        preco: 299.99,
        precoOriginal: 399.99,
        frete: 15,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'BassX',
        numeroModelo: 'BS-01',
        condicao: 'novo',
        dimensoes: '25x10x10 cm',
        garantia: '6 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'PR',
        quantidade: 40,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Roteador Wi-Fi 6 TurboNet',
        descricao: 'Roteador com suporte a Wi-Fi 6 e alta velocidade',
        preco: 399.99,
        precoOriginal: 499.99,
        frete: 20,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'TurboNet',
        numeroModelo: 'RT-AX2000',
        condicao: 'novo',
        dimensoes: '18x12x4 cm',
        garantia: '18 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'SC',
        quantidade: 25,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Webcam Full HD ProCam',
        descricao: 'Webcam com microfone embutido e 1080p',
        preco: 199.99,
        precoOriginal: 249.99,
        frete: 10,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'ProCam',
        numeroModelo: 'PC1080',
        condicao: 'novo',
        dimensoes: '8x3x3 cm',
        garantia: '12 meses',
        voltagem: 'USB',
        localizacaoProduto: 'SP',
        quantidade: 60,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Monitor Gamer 27" Curvo',
        descricao: 'Monitor curvo com taxa de atualização de 165Hz e 1ms de resposta',
        preco: 1899.99,
        precoOriginal: 2199.99,
        frete: 30,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'CurvedG27',
        numeroModelo: 'MG2700C',
        condicao: 'novo',
        dimensoes: '61x36x12 cm',
        garantia: '12 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'SP',
        quantidade: 20,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Console GameStation 5',
        descricao: 'Console de última geração com SSD ultra-rápido e gráficos realistas',
        preco: 4499.99,
        precoOriginal: 4999.99,
        frete: 45,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'GS5',
        numeroModelo: 'GS500X',
        condicao: 'novo',
        dimensoes: '39x26x10 cm',
        garantia: '12 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'RJ',
        quantidade: 15,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Drone Cam 4K Pro',
        descricao: 'Drone com câmera 4K, GPS e estabilizador de imagem',
        preco: 2299.99,
        precoOriginal: 2699.99,
        frete: 35,
        ativo: true,
        categoriaId: categoriaEletronicos.id,
        marcaId: marcaX.id,
        modelo: 'Drone4K',
        numeroModelo: 'D4K-01',
        condicao: 'novo',
        dimensoes: '30x30x10 cm',
        garantia: '12 meses',
        voltagem: 'Bateria',
        localizacaoProduto: 'SC',
        quantidade: 25,
        quantidadeVarejo: 1,
      },
    ],
    skipDuplicates: true,
    skipDuplicates: true,
  });

  // Produtos de Moda
  await prisma.produto.createMany({
    data: [
      {
        nome: 'Jaqueta Jeans Masculina Slim',
        descricao: 'Jaqueta jeans com corte slim e lavagem moderna',
        preco: 179.9,
        precoOriginal: 229.9,
        preco: 179.9,
        precoOriginal: 229.9,
        frete: 22,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'JKT2025',
        numeroModelo: 'JJ001',
        condicao: 'novo',
        dimensoes: '40x30x5 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 60,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Vestido Longo Floral Feminino',
        descricao: 'Vestido leve e elegante, ideal para o verão',
        preco: 139.9,
        precoOriginal: 169.9,
        preco: 139.9,
        precoOriginal: 169.9,
        frete: 18,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'VDL2025',
        numeroModelo: 'VF123',
        condicao: 'novo',
        dimensoes: '35x25x4 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RJ',
        quantidade: 50,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Tênis Esportivo Unissex Corrida Pro',
        descricao: 'Tênis leve com amortecimento para corrida e academia',
        preco: 249.9,
        precoOriginal: 299.9,
        preco: 249.9,
        precoOriginal: 299.9,
        frete: 24,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'RunPro',
        numeroModelo: 'TEN456',
        condicao: 'novo',
        dimensoes: '33x23x12 cm',
        garantia: '6 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'MG',
        quantidade: 40,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Blusa Canelada Gola Alta Feminina',
        descricao: 'Blusa elegante com tecido confortável',
        preco: 69.9,
        precoOriginal: 89.9,
        preco: 69.9,
        precoOriginal: 89.9,
        frete: 12,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'BLGC2025',
        numeroModelo: 'BC789',
        condicao: 'novo',
        dimensoes: '28x20x3 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'PR',
        quantidade: 80,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Camisa Social Masculina Slim Fit',
        descricao: 'Camisa elegante com tecido de alta qualidade',
        preco: 119.9,
        precoOriginal: 149.9,
        preco: 119.9,
        precoOriginal: 149.9,
        frete: 15,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'CS2025',
        numeroModelo: 'CMS234',
        condicao: 'novo',
        dimensoes: '38x28x3 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SC',
        quantidade: 70,
        quantidadeVarejo: 3,
      },
      {
        nome: 'Calça Jeans Skinny Feminina',
        descricao: 'Modelagem que valoriza a silhueta com elastano',
        preco: 129.9,
        precoOriginal: 159.9,
        preco: 129.9,
        precoOriginal: 159.9,
        frete: 16,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'CJ2025',
        numeroModelo: 'CJ985',
        condicao: 'novo',
        dimensoes: '40x25x4 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RS',
        quantidade: 55,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Casaco Moletom Masculino com Capuz',
        descricao: 'Ideal para dias frios com bolso frontal',
        preco: 99.9,
        precoOriginal: 129.9,
        preco: 99.9,
        precoOriginal: 129.9,
        frete: 20,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'MOLETOM25',
        numeroModelo: 'MC005',
        condicao: 'novo',
        dimensoes: '42x32x6 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 90,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Óculos de Sol Estilo Aviador UV400',
        descricao: 'Proteção total contra raios UV e visual moderno',
        preco: 79.9,
        precoOriginal: 109.9,
        preco: 79.9,
        precoOriginal: 109.9,
        frete: 10,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'SUNPRO',
        numeroModelo: 'OC555',
        condicao: 'novo',
        dimensoes: '16x6x6 cm',
        garantia: '6 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'BA',
        quantidade: 100,
        quantidadeVarejo: 4,
      },
      {
        nome: 'Bolsa Feminina Transversal Couro Sintético',
        descricao: 'Compacta, elegante e prática para o dia a dia',
        preco: 109.9,
        precoOriginal: 139.9,
        preco: 109.9,
        precoOriginal: 139.9,
        frete: 14,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'BOLMODA',
        numeroModelo: 'BF678',
        condicao: 'novo',
        dimensoes: '24x18x8 cm',
        garantia: '6 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'CE',
        quantidade: 60,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Relógio Digital Masculino Esportivo',
        descricao: 'Resistente à água, com cronômetro e luz de LED',
        preco: 89.9,
        precoOriginal: 119.9,
        preco: 89.9,
        precoOriginal: 119.9,
        frete: 11,
        ativo: true,
        categoriaId: categoriaModa.id,
        marcaId: marcaX.id,
        modelo: 'SPORTWAT',
        numeroModelo: 'RM101',
        condicao: 'novo',
        dimensoes: '12x8x6 cm',
        garantia: '12 meses',
        voltagem: 'Bateria',
        localizacaoProduto: 'MG',
        quantidade: 75,
        quantidadeVarejo: 2,
      },
    ],
    skipDuplicates: true,
    skipDuplicates: true,
  });

  // Produtos de Casa e Decoração
  await prisma.produto.createMany({
    data: [
      {
        nome: 'Luminária de Mesa Vintage',
        descricao: 'Luminária com design retrô e luz regulável',
        preco: 149.9,
        precoOriginal: 189.9,
        preco: 149.9,
        precoOriginal: 189.9,
        frete: 20,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'LUMVINT',
        numeroModelo: 'LV001',
        condicao: 'novo',
        dimensoes: '30x15x15 cm',
        garantia: '12 meses',
        voltagem: '110V',
        localizacaoProduto: 'SP',
        quantidade: 35,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Conjunto de Almofadas Decorativas 4 Peças',
        descricao: 'Almofadas com estampas modernas e confortáveis',
        preco: 99.9,
        precoOriginal: 129.9,
        preco: 99.9,
        precoOriginal: 129.9,
        frete: 15,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'ALMOF4',
        numeroModelo: 'AC123',
        condicao: 'novo',
        dimensoes: '45x45 cm cada',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RJ',
        quantidade: 60,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Vaso Cerâmico Branco',
        descricao: 'Vaso elegante para plantas ou decoração',
        preco: 79.9,
        precoOriginal: 99.9,
        preco: 79.9,
        precoOriginal: 99.9,
        frete: 18,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'VASO25',
        numeroModelo: 'VC025',
        condicao: 'novo',
        dimensoes: '25x15x15 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'MG',
        quantidade: 80,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Relógio de Parede Minimalista',
        descricao: 'Relógio moderno com design clean e silencioso',
        preco: 129.9,
        precoOriginal: 159.9,
        preco: 129.9,
        precoOriginal: 159.9,
        frete: 20,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'RELOGIO1',
        numeroModelo: 'RP001',
        condicao: 'novo',
        dimensoes: '35x35x5 cm',
        garantia: '12 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'PR',
        quantidade: 40,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Castiçal de Metal Dourado',
        descricao: 'Castiçal elegante para velas decorativas',
        preco: 59.9,
        precoOriginal: 79.9,
        preco: 59.9,
        precoOriginal: 79.9,
        frete: 12,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'CASTMET',
        numeroModelo: 'CM123',
        condicao: 'novo',
        dimensoes: '20x10x10 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RS',
        quantidade: 70,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Tapete Decorativo',
        descricao: 'Tapete macio com design geométrico moderno',
        preco: 299.9,
        precoOriginal: 349.9,
        preco: 299.9,
        precoOriginal: 349.9,
        frete: 40,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'TAP120',
        numeroModelo: 'TP001',
        condicao: 'novo',
        dimensoes: '120x180 cm',
        garantia: '12 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 25,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Espelho Decorativo Redondo',
        descricao: 'Espelho com moldura dourada para sala ou quarto',
        preco: 199.9,
        precoOriginal: 249.9,
        preco: 199.9,
        precoOriginal: 249.9,
        frete: 30,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'ESPREND',
        numeroModelo: 'ED001',
        condicao: 'novo',
        dimensoes: '60x60x5 cm',
        garantia: '12 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RJ',
        quantidade: 30,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Cortina Blackout',
        descricao: 'Cortina bloqueia luz, ideal para quartos',
        preco: 249.9,
        precoOriginal: 299.9,
        preco: 249.9,
        precoOriginal: 299.9,
        frete: 35,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'CORTBLK',
        numeroModelo: 'CB001',
        condicao: 'novo',
        dimensoes: '200x250 cm',
        garantia: '12 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 40,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Prateleira Flutuante',
        descricao: 'Prateleira em MDF para organização e decoração',
        preco: 129.9,
        precoOriginal: 159.9,
        preco: 129.9,
        precoOriginal: 159.9,
        frete: 25,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'PRATFLT',
        numeroModelo: 'PF001',
        condicao: 'novo',
        dimensoes: '80x20x15 cm',
        garantia: '12 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'MG',
        quantidade: 35,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Jogo de Taças Cristal 6 Peças',
        descricao: 'Conjunto elegante para ocasiões especiais',
        preco: 179.9,
        precoOriginal: 219.9,
        preco: 179.9,
        precoOriginal: 219.9,
        frete: 22,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'TAÇCRIS',
        numeroModelo: 'TC006',
        condicao: 'novo',
        dimensoes: '30x30x30 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RS',
        quantidade: 50,
        quantidadeVarejo: 1,
      },
    ],
    skipDuplicates: true,
    skipDuplicates: true,
  });

  // Produtos de Beleza
  // Produtos de Beleza
  await prisma.produto.createMany({
    data: [
      {
        nome: 'Secador Íon Pro 2000W',
        descricao: 'Secador de cabelo com tecnologia de íons, protege os fios do calor excessivo',
        preco: 199.99,
        precoOriginal: 259.99,
        frete: 20,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'IonPro',
        numeroModelo: 'SC2000',
        condicao: 'novo',
        dimensoes: '25x20x10 cm',
        garantia: '6 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'SP',
        quantidade: 40,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Prancha Alisadora Nano Titanium',
        descricao: 'Alisa com precisão e brilho, indicada para todos os tipos de cabelo',
        preco: 279.9,
        precoOriginal: 319.9,
        preco: 279.9,
        precoOriginal: 319.9,
        frete: 25,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'NanoTitanium',
        numeroModelo: 'NT400',
        condicao: 'novo',
        dimensoes: '30x4x5 cm',
        garantia: '12 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'MG',
        quantidade: 35,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Escova Secadora 4 em 1',
        descricao: 'Modela, alisa, seca e dá volume com uma única escova elétrica',
        preco: 169.99,
        precoOriginal: 199.99,
        frete: 18,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'BeautyBrush4in1',
        numeroModelo: 'BB400',
        condicao: 'novo',
        dimensoes: '35x7x7 cm',
        garantia: '6 meses',
        voltagem: '110V',
        localizacaoProduto: 'PR',
        quantidade: 60,
        quantidadeVarejo: 3,
      },
      {
        nome: 'Kit Skincare Completo',
        descricao: 'Limpeza, hidratação e tonificação com produtos dermatologicamente testados',
        preco: 139.9,
        precoOriginal: 169.9,
        preco: 139.9,
        precoOriginal: 169.9,
        frete: 15,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'SkinCare5x',
        numeroModelo: 'SKC05',
        condicao: 'novo',
        dimensoes: '20x15x8 cm',
        garantia: '6 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 100,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Aparador de Pelos Facial Recarregável',
        descricao: 'Remoção delicada de pelos com acabamento suave e indolor',
        preco: 89.9,
        precoOriginal: 119.9,
        preco: 89.9,
        precoOriginal: 119.9,
        frete: 12,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'FacialTrim',
        numeroModelo: 'FT100',
        condicao: 'novo',
        dimensoes: '12x2x2 cm',
        garantia: '6 meses',
        voltagem: 'Bateria',
        localizacaoProduto: 'BA',
        quantidade: 80,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Massageador Facial Sônico',
        descricao: 'Estimula a circulação e promove a absorção de produtos faciais',
        preco: 149.99,
        precoOriginal: 179.99,
        frete: 14,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'SonicGlow',
        numeroModelo: 'MGF300',
        condicao: 'novo',
        dimensoes: '10x6x4 cm',
        garantia: '6 meses',
        voltagem: 'Bateria',
        localizacaoProduto: 'SC',
        quantidade: 60,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Depilador Elétrico Feminino',
        descricao: 'Depilação suave e eficaz com tecnologia de proteção da pele',
        preco: 129.9,
        precoOriginal: 159.9,
        preco: 129.9,
        precoOriginal: 159.9,
        frete: 16,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'SkinSoft',
        numeroModelo: 'DP100',
        condicao: 'novo',
        dimensoes: '14x4x3 cm',
        garantia: '12 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'RJ',
        quantidade: 45,
        quantidadeVarejo: 1,
      },
      {
        nome: 'Kit Maquiagem Profissional',
        descricao: 'Paleta com sombras, blush, iluminador e pó compacto para todos os tons',
        preco: 119.99,
        precoOriginal: 149.99,
        frete: 20,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'MakePro120',
        numeroModelo: 'MKP120',
        condicao: 'novo',
        dimensoes: '30x20x3 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'PE',
        quantidade: 70,
        quantidadeVarejo: 3,
      },
      {
        nome: 'Creme Antissinais com Retinol 50g',
        descricao: 'Reduz linhas de expressão e hidrata profundamente',
        preco: 59.9,
        precoOriginal: 79.9,
        preco: 59.9,
        precoOriginal: 79.9,
        frete: 10,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'RetinolCare',
        numeroModelo: 'RC50',
        condicao: 'novo',
        dimensoes: '12x5x5 cm',
        garantia: 'Sem garantia',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'RS',
        quantidade: 90,
        quantidadeVarejo: 2,
      },
      {
        nome: 'Escova de Cabelo Anti-Frizz',
        descricao: 'Escova alisadora com tecnologia para anti-frizz',
        preco: 189.9,
        precoOriginal: 229.9,
        preco: 189.9,
        precoOriginal: 229.9,
        frete: 22,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'FrizzOut',
        numeroModelo: 'FR200',
        condicao: 'novo',
        dimensoes: '26x8x6 cm',
        garantia: '6 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'SP',
        quantidade: 35,
        quantidadeVarejo: 1,
      },
    ],
    skipDuplicates: true,
    skipDuplicates: true,
  });

  await prisma.midia.createMany({
    data: [
      { link: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e', produtoId: 1 },
      { link: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12', produtoId: 2 },
      { link: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1640&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 3 },
      { link: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 4 },
      { link: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 5 },
      { link: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 6 },
      { link: 'https://images.unsplash.com/photo-1636569826709-8e07f6104992?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 7 },
      { link: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=1684&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 8 },
      { link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_5_and_DualSense.jpg/500px-PlayStation_5_and_DualSense.jpg?20201130152557', produtoId: 9 },
      { link: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 10 },
      { link: 'https://images.unsplash.com/photo-1549108949-89cd83414d5a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 11 },
      { link: 'https://images.unsplash.com/photo-1658955924468-a4ee5fa6aeb6?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 12 },
      { link: 'https://images.unsplash.com/photo-1559743345-60e0907c4853?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 13 },
      { link: 'https://images.unsplash.com/photo-1597582927786-bae43be837a0?q=80&w=1885&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 14 },
      { link: 'https://images.unsplash.com/photo-1656453260540-268a06c29c73?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 15 },
      { link: 'https://images.unsplash.com/photo-1665816152071-4cccdeeb1583?q=80&w=1664&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 16 },
      { link: 'https://images.unsplash.com/photo-1678740268643-aa5777c2f16d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 17 },
      { link: 'https://images.unsplash.com/photo-1653038282392-bbca5f8a3f0d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 18 },
      { link: 'https://images.unsplash.com/photo-1575384938813-188de2f81d1d?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 19 },
      { link: 'https://images.unsplash.com/photo-1733570890170-49be2550189b?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 20 },
      { link: 'https://plus.unsplash.com/premium_photo-1715890451731-dc7e87984313?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 21 },
      { link: 'https://plus.unsplash.com/premium_photo-1682310316833-578612b07de7?q=80&w=1812&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 22 },
      { link: 'https://plus.unsplash.com/premium_photo-1681449855827-295c626f7b84?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 23 },
      { link: 'https://plus.unsplash.com/premium_photo-1664391827302-9d821c39762b?q=80&w=1643&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 24 },
      { link: 'https://images.unsplash.com/photo-1648115315559-620fb2f655aa?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 25 },
      { link: 'https://images.unsplash.com/photo-1576173478758-2ada6f4aa9e2?q=80&w=1833&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 26 },
      { link: 'https://images.unsplash.com/photo-1688731789548-d48e75c02894?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 27 },
      { link: 'https://images.unsplash.com/photo-1660958639203-cbc9bb56955b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 28 },
      { link: 'https://plus.unsplash.com/premium_photo-1739612422471-856ba749b780?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 29 },
      { link: 'https://images.unsplash.com/photo-1694445482967-f3024c92852d?q=80&w=1682&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 30 },
      { link: 'https://images.unsplash.com/photo-1522338140262-f46f5913618a?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 31 },
      { link: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?q=80&w=1826&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 32 },
      { link: 'https://images.unsplash.com/photo-1711454867327-4990937f8f18?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 33 },
      { link: 'https://images.unsplash.com/photo-1629198688000-71f23e745b6e?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 34 },
      { link: 'https://images.unsplash.com/photo-1710839006592-4fdfc6caca80?q=80&w=1760&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 35 },
      { link: 'https://plus.unsplash.com/premium_photo-1661576924581-a2a6c614f53b?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 36 },
      { link: 'https://images.pexels.com/photos/10359950/pexels-photo-10359950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', produtoId: 37 },
      { link: 'https://images.unsplash.com/photo-1602532381225-eec578361933?q=80&w=1630&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 38 },
      { link: 'https://images.pexels.com/photos/5264269/pexels-photo-5264269.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', produtoId: 39 },
      { link: 'https://images.unsplash.com/photo-1703353288357-c7efb9e6573a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', produtoId: 40 },
    ],
    skipDuplicates: true,
  });

  console.log('Seed de Categorias, Marcas, Produtos e Mídias finalizado.');

// Cria um cliente para associar aos pedidos ou busca um existente
  const saltRounds = 10;
  const passwordHash = await bcrypt.hash('senha123', saltRounds);

  const cliente = await prisma.cliente.upsert({
    where: { email: 'joao.silva@example.com' },
    update: {},
    create: {
      nome: 'João Silva',
      email: 'joao.silva@example.com',
      telefone: '11987654321',
      senha: passwordHash,
      dataNascimento: new Date('1990-01-15T00:00:00Z'),
      cpf: '12345678901', // Garanta que este CPF é único no seu banco
      ativo: true,
      verificado: true,
    },
    where: { email: 'maria.oliveira@example.com' },
    update: {},
    create: {
      nome: 'Maria Oliveira',
      email: 'maria.oliveira@example.com',
      telefone: '11987654322',
      senha: passwordHash,
      dataNascimento: new Date('1992-10-10T00:00:00Z'),
      cpf: '12345678957',
      ativo: true,
      verificado: true,
    },
  });
  console.log(`✅ Cliente "${cliente.nome}" (ID: ${cliente.id}) está pronto.`);

  // Busca produtos para usar nos pedidos
  const produto1 = await prisma.produto.findUnique({ where: { id: 1 } });
  const produto11 = await prisma.produto.findUnique({ where: { id: 11 } });
  const produto19 = await prisma.produto.findUnique({ where: { id: 19 } });
  const produto22 = await prisma.produto.findUnique({ where: { id: 22 } });
  const produto31 = await prisma.produto.findUnique({ where: { id: 31 } });

  if (!produto1 || !produto11) {
    console.error('Produtos de exemplo não encontrados. Certifique-se de que os produtos com ID 1 e 11 existem.');
    return;
  }
  // Garante que os produtos específicos para os pedidos existam ou os cria
  // Para o primeiro pedido: "Cadeira de Escritório Ergonômica"
  let produtoPedido1 = await prisma.produto.findFirst({
    where: { nome: 'Cadeira de Escritório Ergonômica' },
  });

  if (!produtoPedido1) {
    console.warn('Produto "Cadeira de Escritório Ergonômica" não encontrado, criando...');
    produtoPedido1 = await prisma.produto.create({
      data: {
        nome: 'Cadeira de Escritório Ergonômica',
        descricao: 'Cadeira confortável com suporte lombar e ajuste de altura.',
        preco: 499.9,
        precoOriginal: 599.9,
        frete: 50,
        ativo: true,
        categoriaId: categoriaCasaDeco.id,
        marcaId: marcaX.id,
        modelo: 'ERGOCAD',
        numeroModelo: 'CE001',
        condicao: 'novo',
        dimensoes: '60x60x110 cm',
        garantia: '24 meses',
        voltagem: 'Não se aplica',
        localizacaoProduto: 'SP',
        quantidade: 35,
        quantidadeVarejo: 1,
      },
    });
  }
  console.log(`✅ Produto para Pedido 1 ("${produtoPedido1.nome}") (ID: ${produtoPedido1.id}) está pronto.`);


  // Para o segundo pedido: "Secador Íon Pro 2000W"
  let produtoPedido2 = await prisma.produto.findFirst({
    where: { nome: 'Secador Íon Pro 2000W' },
  });

  if (!produtoPedido2) {
    console.warn('Produto "Secador Íon Pro 2000W" não encontrado, criando...');
    produtoPedido2 = await prisma.produto.create({
      data: {
        nome: 'Secador Íon Pro 2000W',
        descricao: 'Secador de cabelo com tecnologia de íons, protege os fios do calor excessivo',
        preco: 199.99,
        precoOriginal: 259.99,
        frete: 20,
        ativo: true,
        categoriaId: categoriaBeleza.id,
        marcaId: marcaX.id,
        modelo: 'IonPro',
        numeroModelo: 'SC2000',
        condicao: 'novo',
        dimensoes: '25x20x10 cm',
        garantia: '6 meses',
        voltagem: 'Bivolt',
        localizacaoProduto: 'SP',
        quantidade: 40,
        quantidadeVarejo: 2,
      },
    });
  }
  console.log(`✅ Produto para Pedido 2 ("${produtoPedido2.nome}") (ID: ${produtoPedido2.id}) está pronto.`);

  // Cria Pedidos
  await prisma.pedido.createMany({
    data: [
      // ✅ SEMANA
      {
        quantidade: 1,
        clienteId: cliente.id,
        dataCompra: new Date('2025-06-10T09:00:00Z'),
        produtoId: produto1.id,
        formaPagamento: 'Cartão de Crédito',
        status: 'pago',
        valorPago: produto1.preco,
        dataEntrega: new Date('2025-06-13T18:00:00Z'),
        notaFiscal: 'NF-10001',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },
      {
        quantidade: 2,
        clienteId: cliente.id,
        dataCompra: new Date('2025-06-11T14:00:00Z'),
        produtoId: produto22.id,
        formaPagamento: 'Pix',
        status: 'pago',
        valorPago: Number(produto22.preco) * 2,
        dataEntrega: new Date('2025-06-15T18:00:00Z'),
        notaFiscal: 'NF-10002',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },
      {
        quantidade: 1,
        clienteId: cliente.id,
        dataCompra: new Date('2025-06-13T16:45:00Z'),
        produtoId: produto31.id,
        formaPagamento: 'Boleto',
        status: 'pago',
        valorPago: produto31.preco,
        dataEntrega: new Date('2025-06-16T18:00:00Z'),
        notaFiscal: 'NF-10003',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },

      // ✅ MÊS (fora da semana)
      {
        quantidade: 1,
        clienteId: cliente.id,
        dataCompra: new Date('2025-05-20T11:20:00Z'),
        produtoId: produto1.id,
        formaPagamento: 'Pix',
        status: 'pago',
        valorPago: produto1.preco,
        dataEntrega: new Date('2025-05-25T18:00:00Z'),
        notaFiscal: 'NF-10004',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },
      {
        quantidade: 2,
        clienteId: cliente.id,
        dataCompra: new Date('2025-05-28T13:15:00Z'),
        produtoId: produto19.id,
        formaPagamento: 'Cartão de Débito',
        status: 'pago',
        valorPago: Number(produto19.preco) * 2,
        dataEntrega: new Date('2025-06-02T18:00:00Z'),
        notaFiscal: 'NF-10005',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },

      // ❌ FORA DO MÊS
      {
        quantidade: 1,
        clienteId: cliente.id,
        dataCompra: new Date('2025-04-10T10:00:00Z'),
        produtoId: produto1.id,
        formaPagamento: 'Boleto',
        status: 'pago',
        valorPago: produto1.preco,
        dataEntrega: new Date('2025-04-15T18:00:00Z'),
        notaFiscal: 'NF-10006',
        dataDevolucao: new Date('9999-12-31T23:59:59Z'),
        assinado: 'João Silva',
      },
    ],
    skipDuplicates: true,
  });

  console.log('Cliente e Pedidos semeados com sucesso!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });